# This file was generated by GoReleaser. DO NOT EDIT.
cask "meetap" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "e0da72d66a74879f2f9aca749c2562afdd17a9139d1a59ae3dc43953dccea88c"
      url "https://github.com/marimelon/meetap/releases/download/v#{version}/meetap-darwin-arm64",
        verified: "github.com/marimelon/meetap"
      binary "meetap-darwin-arm64", target: "meetap"
    end
  end

  name "meetap"
  desc "macOS system audio + mic recorder with whisper.cpp transcription"
  homepage "https://github.com/marimelon/meetap"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

  caveats <<~EOS
    whisper モデルの初回ダウンロードが必要です。
    詳細: https://github.com/marimelon/meetap#whisper-モデルのセットアップ
  EOS
end
